# config/default.yaml
server:
  host: "0.0.0.0"
  port: 5000
  workers: 4
  debug: false

etcd:
  host: "localhost"
  port: 2379
  timeout: 5
  retry_interval: 1
  max_retries: 10

graphql:
  path: "/graphql"
  graphiql: true
  batch: true
  max_depth: 10

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

hypervisor:
  type: "docker" 
